In [1]:
!pip install kafka-python

Collecting kafka-python
  Downloading kafka_python-3.0.1-py3-none-any.whl.metadata (11 kB)
Downloading kafka_python-3.0.1-py3-none-any.whl (606 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 606.4/606.4 kB 10.1 MB/s eta 0:00:00
Installing collected packages: kafka-python
Successfully installed kafka-python-3.0.1

In [3]:
import pandas as pd

df = pd.read_csv(
    "/content/Integrated_Customer_Data.csv"
)

df.head()

,CustomerID,TotalSales,Quantity,NumOrders,Customer_ID,BirthYear,Education,Marital_Status,Income,Kidhome,...,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Age,AgeGroup
0,12346,0.00,0,2,5524,1957,Graduation,Single,58138.0,0,...,0,0,0,0,0,3,11,1,68,Senior
1,12347,4310.00,2458,7,2174,1954,Graduation,Single,46344.0,1,...,0,0,0,0,0,3,11,0,71,Senior
2,12348,1797.24,2341,4,4141,1965,Graduation,Together,71613.0,0,...,0,0,0,0,0,3,11,0,60,Middle Age
3,12349,1757.55,631,1,6182,1984,Graduation,Together,26646.0,1,...,0,0,0,0,0,3,11,0,41,Adult
4,12350,334.40,197,1,5324,1981,PhD,Married,58293.0,1,...,0,0,0,0,0,3,11,0,44,Adult

In [4]:
import json
import time

records = df.head(20)

for index, row in records.iterrows():

    message = row.to_dict()

    print(
        "Sending:",
        json.dumps(message)
    )

    time.sleep(1)

Sending: {"CustomerID": 12346, "TotalSales": 0.0, "Quantity": 0, "NumOrders": 2, "Customer_ID": 5524, "BirthYear": 1957, "Education": "Graduation", "Marital_Status": "Single", "Income": 58138.0, "Kidhome": 0, "Teenhome": 0, "Dt_Customer": "04-09-2012", "Recency": 58, "MntWines": 635, "MntFruits": 88, "MntMeatProducts": 546, "MntFishProducts": 172, "MntSweetProducts": 88, "MntGoldProds": 88, "NumDealsPurchases": 3, "NumWebPurchases": 8, "NumCatalogPurchases": 10, "NumStorePurchases": 4, "NumWebVisitsMonth": 7, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 0, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 1, "Age": 68, "AgeGroup": "Senior"}
Sending: {"CustomerID": 12347, "TotalSales": 4310.0, "Quantity": 2458, "NumOrders": 7, "Customer_ID": 2174, "BirthYear": 1954, "Education": "Graduation", "Marital_Status": "Single", "Income": 46344.0, "Kidhome": 1, "Teenhome": 1, "Dt_Customer": "08-03-2014", "Recency": 38, "MntWines": 11, "MntFruits": 1, "MntMeatProducts": 6, "MntFishProducts": 2, "MntSweetProducts": 1, "MntGoldProds": 6, "NumDealsPurchases": 2, "NumWebPurchases": 1, "NumCatalogPurchases": 1, "NumStorePurchases": 2, "NumWebVisitsMonth": 5, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 0, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 0, "Age": 71, "AgeGroup": "Senior"}
Sending: {"CustomerID": 12348, "TotalSales": 1797.24, "Quantity": 2341, "NumOrders": 4, "Customer_ID": 4141, "BirthYear": 1965, "Education": "Graduation", "Marital_Status": "Together", "Income": 71613.0, "Kidhome": 0, "Teenhome": 0, "Dt_Customer": "21-08-2013", "Recency": 26, "MntWines": 426, "MntFruits": 49, "MntMeatProducts": 127, "MntFishProducts": 111, "MntSweetProducts": 21, "MntGoldProds": 42, "NumDealsPurchases": 1, "NumWebPurchases": 8, "NumCatalogPurchases": 2, "NumStorePurchases": 10, "NumWebVisitsMonth": 4, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 0, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 0, "Age": 60, "AgeGroup": "Middle Age"}
Sending: {"CustomerID": 12349, "TotalSales": 1757.55, "Quantity": 631, "NumOrders": 1, "Customer_ID": 6182, "BirthYear": 1984, "Education": "Graduation", "Marital_Status": "Together", "Income": 26646.0, "Kidhome": 1, "Teenhome": 0, "Dt_Customer": "10-02-2014", "Recency": 26, "MntWines": 11, "MntFruits": 4, "MntMeatProducts": 20, "MntFishProducts": 10, "MntSweetProducts": 3, "MntGoldProds": 5, "NumDealsPurchases": 2, "NumWebPurchases": 2, "NumCatalogPurchases": 0, "NumStorePurchases": 4, "NumWebVisitsMonth": 6, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 0, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 0, "Age": 41, "AgeGroup": "Adult"}
Sending: {"CustomerID": 12350, "TotalSales": 334.4, "Quantity": 197, "NumOrders": 1, "Customer_ID": 5324, "BirthYear": 1981, "Education": "PhD", "Marital_Status": "Married", "Income": 58293.0, "Kidhome": 1, "Teenhome": 0, "Dt_Customer": "19-01-2014", "Recency": 94, "MntWines": 173, "MntFruits": 43, "MntMeatProducts": 118, "MntFishProducts": 46, "MntSweetProducts": 27, "MntGoldProds": 15, "NumDealsPurchases": 5, "NumWebPurchases": 5, "NumCatalogPurchases": 3, "NumStorePurchases": 6, "NumWebVisitsMonth": 5, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 0, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 0, "Age": 44, "AgeGroup": "Adult"}
Sending: {"CustomerID": 12352, "TotalSales": 1545.41, "Quantity": 470, "NumOrders": 11, "Customer_ID": 7446, "BirthYear": 1967, "Education": "Master", "Marital_Status": "Together", "Income": 62513.0, "Kidhome": 0, "Teenhome": 1, "Dt_Customer": "09-09-2013", "Recency": 16, "MntWines": 520, "MntFruits": 42, "MntMeatProducts": 98, "MntFishProducts": 0, "MntSweetProducts": 42, "MntGoldProds": 14, "NumDealsPurchases": 2, "NumWebPurchases": 6, "NumCatalogPurchases": 4, "NumStorePurchases": 10, "NumWebVisitsMonth": 6, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 0, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 0, "Age": 58, "AgeGroup": "Middle Age"}
Sending: {"CustomerID": 12353, "TotalSales": 89.0, "Quantity": 20, "NumOrders": 1, "Customer_ID": 965, "BirthYear": 1971, "Education": "Graduation", "Marital_Status": "Divorced", "Income": 55635.0, "Kidhome": 0, "Teenhome": 1, "Dt_Customer": "13-11-2012", "Recency": 34, "MntWines": 235, "MntFruits": 65, "MntMeatProducts": 164, "MntFishProducts": 50, "MntSweetProducts": 49, "MntGoldProds": 27, "NumDealsPurchases": 4, "NumWebPurchases": 7, "NumCatalogPurchases": 3, "NumStorePurchases": 7, "NumWebVisitsMonth": 6, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 0, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 0, "Age": 54, "AgeGroup": "Middle Age"}
Sending: {"CustomerID": 12354, "TotalSales": 1079.4, "Quantity": 530, "NumOrders": 1, "Customer_ID": 6177, "BirthYear": 1985, "Education": "PhD", "Marital_Status": "Married", "Income": 33454.0, "Kidhome": 1, "Teenhome": 0, "Dt_Customer": "08-05-2013", "Recency": 32, "MntWines": 76, "MntFruits": 10, "MntMeatProducts": 56, "MntFishProducts": 3, "MntSweetProducts": 1, "MntGoldProds": 23, "NumDealsPurchases": 2, "NumWebPurchases": 4, "NumCatalogPurchases": 0, "NumStorePurchases": 4, "NumWebVisitsMonth": 8, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 0, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 0, "Age": 40, "AgeGroup": "Adult"}
Sending: {"CustomerID": 12355, "TotalSales": 459.4, "Quantity": 240, "NumOrders": 1, "Customer_ID": 4855, "BirthYear": 1974, "Education": "PhD", "Marital_Status": "Together", "Income": 30351.0, "Kidhome": 1, "Teenhome": 0, "Dt_Customer": "06-06-2013", "Recency": 19, "MntWines": 14, "MntFruits": 0, "MntMeatProducts": 24, "MntFishProducts": 3, "MntSweetProducts": 3, "MntGoldProds": 2, "NumDealsPurchases": 1, "NumWebPurchases": 3, "NumCatalogPurchases": 0, "NumStorePurchases": 2, "NumWebVisitsMonth": 9, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 0, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 1, "Age": 51, "AgeGroup": "Middle Age"}
Sending: {"CustomerID": 12356, "TotalSales": 2811.43, "Quantity": 1591, "NumOrders": 3, "Customer_ID": 5899, "BirthYear": 1950, "Education": "PhD", "Marital_Status": "Together", "Income": 5648.0, "Kidhome": 1, "Teenhome": 1, "Dt_Customer": "13-03-2014", "Recency": 68, "MntWines": 28, "MntFruits": 0, "MntMeatProducts": 6, "MntFishProducts": 1, "MntSweetProducts": 1, "MntGoldProds": 13, "NumDealsPurchases": 1, "NumWebPurchases": 1, "NumCatalogPurchases": 0, "NumStorePurchases": 0, "NumWebVisitsMonth": 20, "AcceptedCmp3": 1, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 0, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 0, "Age": 75, "AgeGroup": "Senior"}
Sending: {"CustomerID": 12357, "TotalSales": 6207.67, "Quantity": 2708, "NumOrders": 1, "Customer_ID": 1994, "BirthYear": 1983, "Education": "Graduation", "Marital_Status": "Married", "Income": 51381.5, "Kidhome": 1, "Teenhome": 0, "Dt_Customer": "15-11-2013", "Recency": 11, "MntWines": 5, "MntFruits": 5, "MntMeatProducts": 6, "MntFishProducts": 0, "MntSweetProducts": 2, "MntGoldProds": 1, "NumDealsPurchases": 1, "NumWebPurchases": 1, "NumCatalogPurchases": 0, "NumStorePurchases": 2, "NumWebVisitsMonth": 7, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 0, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 0, "Age": 42, "AgeGroup": "Adult"}
Sending: {"CustomerID": 12358, "TotalSales": 1168.06, "Quantity": 248, "NumOrders": 2, "Customer_ID": 387, "BirthYear": 1976, "Education": "Basic", "Marital_Status": "Married", "Income": 7500.0, "Kidhome": 0, "Teenhome": 0, "Dt_Customer": "13-11-2012", "Recency": 59, "MntWines": 6, "MntFruits": 16, "MntMeatProducts": 11, "MntFishProducts": 11, "MntSweetProducts": 1, "MntGoldProds": 16, "NumDealsPurchases": 1, "NumWebPurchases": 2, "NumCatalogPurchases": 0, "NumStorePurchases": 3, "NumWebVisitsMonth": 8, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 0, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 0, "Age": 49, "AgeGroup": "Middle Age"}
Sending: {"CustomerID": 12359, "TotalSales": 6182.98, "Quantity": 1599, "NumOrders": 6, "Customer_ID": 2125, "BirthYear": 1959, "Education": "Graduation", "Marital_Status": "Divorced", "Income": 63033.0, "Kidhome": 0, "Teenhome": 0, "Dt_Customer": "15-11-2013", "Recency": 82, "MntWines": 194, "MntFruits": 61, "MntMeatProducts": 480, "MntFishProducts": 225, "MntSweetProducts": 112, "MntGoldProds": 30, "NumDealsPurchases": 1, "NumWebPurchases": 3, "NumCatalogPurchases": 4, "NumStorePurchases": 8, "NumWebVisitsMonth": 2, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 0, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 0, "Age": 66, "AgeGroup": "Senior"}
Sending: {"CustomerID": 12360, "TotalSales": 2662.06, "Quantity": 1165, "NumOrders": 3, "Customer_ID": 8180, "BirthYear": 1952, "Education": "Master", "Marital_Status": "Divorced", "Income": 59354.0, "Kidhome": 1, "Teenhome": 1, "Dt_Customer": "15-11-2013", "Recency": 53, "MntWines": 233, "MntFruits": 2, "MntMeatProducts": 53, "MntFishProducts": 3, "MntSweetProducts": 5, "MntGoldProds": 14, "NumDealsPurchases": 3, "NumWebPurchases": 6, "NumCatalogPurchases": 1, "NumStorePurchases": 5, "NumWebVisitsMonth": 6, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 0, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 0, "Age": 73, "AgeGroup": "Senior"}
Sending: {"CustomerID": 12361, "TotalSales": 189.9, "Quantity": 91, "NumOrders": 1, "Customer_ID": 2569, "BirthYear": 1987, "Education": "Graduation", "Marital_Status": "Married", "Income": 17323.0, "Kidhome": 0, "Teenhome": 0, "Dt_Customer": "10-10-2012", "Recency": 38, "MntWines": 3, "MntFruits": 14, "MntMeatProducts": 17, "MntFishProducts": 6, "MntSweetProducts": 1, "MntGoldProds": 5, "NumDealsPurchases": 1, "NumWebPurchases": 1, "NumCatalogPurchases": 0, "NumStorePurchases": 3, "NumWebVisitsMonth": 8, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 0, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 0, "Age": 38, "AgeGroup": "Adult"}
Sending: {"CustomerID": 12362, "TotalSales": 5154.58, "Quantity": 2212, "NumOrders": 13, "Customer_ID": 2114, "BirthYear": 1946, "Education": "PhD", "Marital_Status": "Single", "Income": 82800.0, "Kidhome": 0, "Teenhome": 0, "Dt_Customer": "24-11-2012", "Recency": 23, "MntWines": 1006, "MntFruits": 22, "MntMeatProducts": 115, "MntFishProducts": 59, "MntSweetProducts": 68, "MntGoldProds": 45, "NumDealsPurchases": 1, "NumWebPurchases": 7, "NumCatalogPurchases": 6, "NumStorePurchases": 12, "NumWebVisitsMonth": 3, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 1, "AcceptedCmp1": 1, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 1, "Age": 79, "AgeGroup": "Senior"}
Sending: {"CustomerID": 12363, "TotalSales": 552.0, "Quantity": 408, "NumOrders": 2, "Customer_ID": 9736, "BirthYear": 1980, "Education": "Graduation", "Marital_Status": "Married", "Income": 41850.0, "Kidhome": 1, "Teenhome": 1, "Dt_Customer": "24-12-2012", "Recency": 51, "MntWines": 53, "MntFruits": 5, "MntMeatProducts": 19, "MntFishProducts": 2, "MntSweetProducts": 13, "MntGoldProds": 4, "NumDealsPurchases": 3, "NumWebPurchases": 3, "NumCatalogPurchases": 0, "NumStorePurchases": 3, "NumWebVisitsMonth": 8, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 0, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 0, "Age": 45, "AgeGroup": "Adult"}
Sending: {"CustomerID": 12364, "TotalSales": 1313.1, "Quantity": 1506, "NumOrders": 4, "Customer_ID": 4939, "BirthYear": 1946, "Education": "Graduation", "Marital_Status": "Together", "Income": 37760.0, "Kidhome": 0, "Teenhome": 0, "Dt_Customer": "31-08-2012", "Recency": 20, "MntWines": 84, "MntFruits": 5, "MntMeatProducts": 38, "MntFishProducts": 150, "MntSweetProducts": 12, "MntGoldProds": 28, "NumDealsPurchases": 2, "NumWebPurchases": 4, "NumCatalogPurchases": 1, "NumStorePurchases": 6, "NumWebVisitsMonth": 7, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 0, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 0, "Age": 79, "AgeGroup": "Senior"}
Sending: {"CustomerID": 12365, "TotalSales": 320.69, "Quantity": 173, "NumOrders": 3, "Customer_ID": 6565, "BirthYear": 1949, "Education": "Master", "Marital_Status": "Married", "Income": 76995.0, "Kidhome": 0, "Teenhome": 1, "Dt_Customer": "28-03-2013", "Recency": 91, "MntWines": 1012, "MntFruits": 80, "MntMeatProducts": 498, "MntFishProducts": 0, "MntSweetProducts": 16, "MntGoldProds": 176, "NumDealsPurchases": 2, "NumWebPurchases": 11, "NumCatalogPurchases": 4, "NumStorePurchases": 9, "NumWebVisitsMonth": 5, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 1, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 0, "Age": 76, "AgeGroup": "Senior"}
Sending: {"CustomerID": 12367, "TotalSales": 168.9, "Quantity": 173, "NumOrders": 1, "Customer_ID": 2278, "BirthYear": 1985, "Education": "2n Cycle", "Marital_Status": "Single", "Income": 33812.0, "Kidhome": 1, "Teenhome": 0, "Dt_Customer": "03-11-2012", "Recency": 86, "MntWines": 4, "MntFruits": 17, "MntMeatProducts": 19, "MntFishProducts": 30, "MntSweetProducts": 24, "MntGoldProds": 39, "NumDealsPurchases": 2, "NumWebPurchases": 2, "NumCatalogPurchases": 1, "NumStorePurchases": 3, "NumWebVisitsMonth": 6, "AcceptedCmp3": 0, "AcceptedCmp4": 0, "AcceptedCmp5": 0, "AcceptedCmp1": 0, "AcceptedCmp2": 0, "Complain": 0, "Z_CostContact": 3, "Z_Revenue": 11, "Response": 0, "Age": 40, "AgeGroup": "Adult"}

In [5]:
stream_messages = []

for index, row in records.iterrows():

    stream_messages.append(
        row.to_dict()
    )

print(
    "Messages in Stream:",
    len(stream_messages)
)

Messages in Stream: 20

In [6]:
for message in stream_messages:

    print(
        "Received:",
        message
    )

Received: {'CustomerID': 12346, 'TotalSales': 0.0, 'Quantity': 0, 'NumOrders': 2, 'Customer_ID': 5524, 'BirthYear': 1957, 'Education': 'Graduation', 'Marital_Status': 'Single', 'Income': 58138.0, 'Kidhome': 0, 'Teenhome': 0, 'Dt_Customer': '04-09-2012', 'Recency': 58, 'MntWines': 635, 'MntFruits': 88, 'MntMeatProducts': 546, 'MntFishProducts': 172, 'MntSweetProducts': 88, 'MntGoldProds': 88, 'NumDealsPurchases': 3, 'NumWebPurchases': 8, 'NumCatalogPurchases': 10, 'NumStorePurchases': 4, 'NumWebVisitsMonth': 7, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 0, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 1, 'Age': 68, 'AgeGroup': 'Senior'}
Received: {'CustomerID': 12347, 'TotalSales': 4310.0, 'Quantity': 2458, 'NumOrders': 7, 'Customer_ID': 2174, 'BirthYear': 1954, 'Education': 'Graduation', 'Marital_Status': 'Single', 'Income': 46344.0, 'Kidhome': 1, 'Teenhome': 1, 'Dt_Customer': '08-03-2014', 'Recency': 38, 'MntWines': 11, 'MntFruits': 1, 'MntMeatProducts': 6, 'MntFishProducts': 2, 'MntSweetProducts': 1, 'MntGoldProds': 6, 'NumDealsPurchases': 2, 'NumWebPurchases': 1, 'NumCatalogPurchases': 1, 'NumStorePurchases': 2, 'NumWebVisitsMonth': 5, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 0, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 0, 'Age': 71, 'AgeGroup': 'Senior'}
Received: {'CustomerID': 12348, 'TotalSales': 1797.24, 'Quantity': 2341, 'NumOrders': 4, 'Customer_ID': 4141, 'BirthYear': 1965, 'Education': 'Graduation', 'Marital_Status': 'Together', 'Income': 71613.0, 'Kidhome': 0, 'Teenhome': 0, 'Dt_Customer': '21-08-2013', 'Recency': 26, 'MntWines': 426, 'MntFruits': 49, 'MntMeatProducts': 127, 'MntFishProducts': 111, 'MntSweetProducts': 21, 'MntGoldProds': 42, 'NumDealsPurchases': 1, 'NumWebPurchases': 8, 'NumCatalogPurchases': 2, 'NumStorePurchases': 10, 'NumWebVisitsMonth': 4, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 0, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 0, 'Age': 60, 'AgeGroup': 'Middle Age'}
Received: {'CustomerID': 12349, 'TotalSales': 1757.55, 'Quantity': 631, 'NumOrders': 1, 'Customer_ID': 6182, 'BirthYear': 1984, 'Education': 'Graduation', 'Marital_Status': 'Together', 'Income': 26646.0, 'Kidhome': 1, 'Teenhome': 0, 'Dt_Customer': '10-02-2014', 'Recency': 26, 'MntWines': 11, 'MntFruits': 4, 'MntMeatProducts': 20, 'MntFishProducts': 10, 'MntSweetProducts': 3, 'MntGoldProds': 5, 'NumDealsPurchases': 2, 'NumWebPurchases': 2, 'NumCatalogPurchases': 0, 'NumStorePurchases': 4, 'NumWebVisitsMonth': 6, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 0, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 0, 'Age': 41, 'AgeGroup': 'Adult'}
Received: {'CustomerID': 12350, 'TotalSales': 334.4, 'Quantity': 197, 'NumOrders': 1, 'Customer_ID': 5324, 'BirthYear': 1981, 'Education': 'PhD', 'Marital_Status': 'Married', 'Income': 58293.0, 'Kidhome': 1, 'Teenhome': 0, 'Dt_Customer': '19-01-2014', 'Recency': 94, 'MntWines': 173, 'MntFruits': 43, 'MntMeatProducts': 118, 'MntFishProducts': 46, 'MntSweetProducts': 27, 'MntGoldProds': 15, 'NumDealsPurchases': 5, 'NumWebPurchases': 5, 'NumCatalogPurchases': 3, 'NumStorePurchases': 6, 'NumWebVisitsMonth': 5, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 0, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 0, 'Age': 44, 'AgeGroup': 'Adult'}
Received: {'CustomerID': 12352, 'TotalSales': 1545.41, 'Quantity': 470, 'NumOrders': 11, 'Customer_ID': 7446, 'BirthYear': 1967, 'Education': 'Master', 'Marital_Status': 'Together', 'Income': 62513.0, 'Kidhome': 0, 'Teenhome': 1, 'Dt_Customer': '09-09-2013', 'Recency': 16, 'MntWines': 520, 'MntFruits': 42, 'MntMeatProducts': 98, 'MntFishProducts': 0, 'MntSweetProducts': 42, 'MntGoldProds': 14, 'NumDealsPurchases': 2, 'NumWebPurchases': 6, 'NumCatalogPurchases': 4, 'NumStorePurchases': 10, 'NumWebVisitsMonth': 6, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 0, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 0, 'Age': 58, 'AgeGroup': 'Middle Age'}
Received: {'CustomerID': 12353, 'TotalSales': 89.0, 'Quantity': 20, 'NumOrders': 1, 'Customer_ID': 965, 'BirthYear': 1971, 'Education': 'Graduation', 'Marital_Status': 'Divorced', 'Income': 55635.0, 'Kidhome': 0, 'Teenhome': 1, 'Dt_Customer': '13-11-2012', 'Recency': 34, 'MntWines': 235, 'MntFruits': 65, 'MntMeatProducts': 164, 'MntFishProducts': 50, 'MntSweetProducts': 49, 'MntGoldProds': 27, 'NumDealsPurchases': 4, 'NumWebPurchases': 7, 'NumCatalogPurchases': 3, 'NumStorePurchases': 7, 'NumWebVisitsMonth': 6, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 0, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 0, 'Age': 54, 'AgeGroup': 'Middle Age'}
Received: {'CustomerID': 12354, 'TotalSales': 1079.4, 'Quantity': 530, 'NumOrders': 1, 'Customer_ID': 6177, 'BirthYear': 1985, 'Education': 'PhD', 'Marital_Status': 'Married', 'Income': 33454.0, 'Kidhome': 1, 'Teenhome': 0, 'Dt_Customer': '08-05-2013', 'Recency': 32, 'MntWines': 76, 'MntFruits': 10, 'MntMeatProducts': 56, 'MntFishProducts': 3, 'MntSweetProducts': 1, 'MntGoldProds': 23, 'NumDealsPurchases': 2, 'NumWebPurchases': 4, 'NumCatalogPurchases': 0, 'NumStorePurchases': 4, 'NumWebVisitsMonth': 8, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 0, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 0, 'Age': 40, 'AgeGroup': 'Adult'}
Received: {'CustomerID': 12355, 'TotalSales': 459.4, 'Quantity': 240, 'NumOrders': 1, 'Customer_ID': 4855, 'BirthYear': 1974, 'Education': 'PhD', 'Marital_Status': 'Together', 'Income': 30351.0, 'Kidhome': 1, 'Teenhome': 0, 'Dt_Customer': '06-06-2013', 'Recency': 19, 'MntWines': 14, 'MntFruits': 0, 'MntMeatProducts': 24, 'MntFishProducts': 3, 'MntSweetProducts': 3, 'MntGoldProds': 2, 'NumDealsPurchases': 1, 'NumWebPurchases': 3, 'NumCatalogPurchases': 0, 'NumStorePurchases': 2, 'NumWebVisitsMonth': 9, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 0, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 1, 'Age': 51, 'AgeGroup': 'Middle Age'}
Received: {'CustomerID': 12356, 'TotalSales': 2811.43, 'Quantity': 1591, 'NumOrders': 3, 'Customer_ID': 5899, 'BirthYear': 1950, 'Education': 'PhD', 'Marital_Status': 'Together', 'Income': 5648.0, 'Kidhome': 1, 'Teenhome': 1, 'Dt_Customer': '13-03-2014', 'Recency': 68, 'MntWines': 28, 'MntFruits': 0, 'MntMeatProducts': 6, 'MntFishProducts': 1, 'MntSweetProducts': 1, 'MntGoldProds': 13, 'NumDealsPurchases': 1, 'NumWebPurchases': 1, 'NumCatalogPurchases': 0, 'NumStorePurchases': 0, 'NumWebVisitsMonth': 20, 'AcceptedCmp3': 1, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 0, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 0, 'Age': 75, 'AgeGroup': 'Senior'}
Received: {'CustomerID': 12357, 'TotalSales': 6207.67, 'Quantity': 2708, 'NumOrders': 1, 'Customer_ID': 1994, 'BirthYear': 1983, 'Education': 'Graduation', 'Marital_Status': 'Married', 'Income': 51381.5, 'Kidhome': 1, 'Teenhome': 0, 'Dt_Customer': '15-11-2013', 'Recency': 11, 'MntWines': 5, 'MntFruits': 5, 'MntMeatProducts': 6, 'MntFishProducts': 0, 'MntSweetProducts': 2, 'MntGoldProds': 1, 'NumDealsPurchases': 1, 'NumWebPurchases': 1, 'NumCatalogPurchases': 0, 'NumStorePurchases': 2, 'NumWebVisitsMonth': 7, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 0, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 0, 'Age': 42, 'AgeGroup': 'Adult'}
Received: {'CustomerID': 12358, 'TotalSales': 1168.06, 'Quantity': 248, 'NumOrders': 2, 'Customer_ID': 387, 'BirthYear': 1976, 'Education': 'Basic', 'Marital_Status': 'Married', 'Income': 7500.0, 'Kidhome': 0, 'Teenhome': 0, 'Dt_Customer': '13-11-2012', 'Recency': 59, 'MntWines': 6, 'MntFruits': 16, 'MntMeatProducts': 11, 'MntFishProducts': 11, 'MntSweetProducts': 1, 'MntGoldProds': 16, 'NumDealsPurchases': 1, 'NumWebPurchases': 2, 'NumCatalogPurchases': 0, 'NumStorePurchases': 3, 'NumWebVisitsMonth': 8, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 0, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 0, 'Age': 49, 'AgeGroup': 'Middle Age'}
Received: {'CustomerID': 12359, 'TotalSales': 6182.98, 'Quantity': 1599, 'NumOrders': 6, 'Customer_ID': 2125, 'BirthYear': 1959, 'Education': 'Graduation', 'Marital_Status': 'Divorced', 'Income': 63033.0, 'Kidhome': 0, 'Teenhome': 0, 'Dt_Customer': '15-11-2013', 'Recency': 82, 'MntWines': 194, 'MntFruits': 61, 'MntMeatProducts': 480, 'MntFishProducts': 225, 'MntSweetProducts': 112, 'MntGoldProds': 30, 'NumDealsPurchases': 1, 'NumWebPurchases': 3, 'NumCatalogPurchases': 4, 'NumStorePurchases': 8, 'NumWebVisitsMonth': 2, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 0, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 0, 'Age': 66, 'AgeGroup': 'Senior'}
Received: {'CustomerID': 12360, 'TotalSales': 2662.06, 'Quantity': 1165, 'NumOrders': 3, 'Customer_ID': 8180, 'BirthYear': 1952, 'Education': 'Master', 'Marital_Status': 'Divorced', 'Income': 59354.0, 'Kidhome': 1, 'Teenhome': 1, 'Dt_Customer': '15-11-2013', 'Recency': 53, 'MntWines': 233, 'MntFruits': 2, 'MntMeatProducts': 53, 'MntFishProducts': 3, 'MntSweetProducts': 5, 'MntGoldProds': 14, 'NumDealsPurchases': 3, 'NumWebPurchases': 6, 'NumCatalogPurchases': 1, 'NumStorePurchases': 5, 'NumWebVisitsMonth': 6, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 0, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 0, 'Age': 73, 'AgeGroup': 'Senior'}
Received: {'CustomerID': 12361, 'TotalSales': 189.9, 'Quantity': 91, 'NumOrders': 1, 'Customer_ID': 2569, 'BirthYear': 1987, 'Education': 'Graduation', 'Marital_Status': 'Married', 'Income': 17323.0, 'Kidhome': 0, 'Teenhome': 0, 'Dt_Customer': '10-10-2012', 'Recency': 38, 'MntWines': 3, 'MntFruits': 14, 'MntMeatProducts': 17, 'MntFishProducts': 6, 'MntSweetProducts': 1, 'MntGoldProds': 5, 'NumDealsPurchases': 1, 'NumWebPurchases': 1, 'NumCatalogPurchases': 0, 'NumStorePurchases': 3, 'NumWebVisitsMonth': 8, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 0, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 0, 'Age': 38, 'AgeGroup': 'Adult'}
Received: {'CustomerID': 12362, 'TotalSales': 5154.58, 'Quantity': 2212, 'NumOrders': 13, 'Customer_ID': 2114, 'BirthYear': 1946, 'Education': 'PhD', 'Marital_Status': 'Single', 'Income': 82800.0, 'Kidhome': 0, 'Teenhome': 0, 'Dt_Customer': '24-11-2012', 'Recency': 23, 'MntWines': 1006, 'MntFruits': 22, 'MntMeatProducts': 115, 'MntFishProducts': 59, 'MntSweetProducts': 68, 'MntGoldProds': 45, 'NumDealsPurchases': 1, 'NumWebPurchases': 7, 'NumCatalogPurchases': 6, 'NumStorePurchases': 12, 'NumWebVisitsMonth': 3, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 1, 'AcceptedCmp1': 1, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 1, 'Age': 79, 'AgeGroup': 'Senior'}
Received: {'CustomerID': 12363, 'TotalSales': 552.0, 'Quantity': 408, 'NumOrders': 2, 'Customer_ID': 9736, 'BirthYear': 1980, 'Education': 'Graduation', 'Marital_Status': 'Married', 'Income': 41850.0, 'Kidhome': 1, 'Teenhome': 1, 'Dt_Customer': '24-12-2012', 'Recency': 51, 'MntWines': 53, 'MntFruits': 5, 'MntMeatProducts': 19, 'MntFishProducts': 2, 'MntSweetProducts': 13, 'MntGoldProds': 4, 'NumDealsPurchases': 3, 'NumWebPurchases': 3, 'NumCatalogPurchases': 0, 'NumStorePurchases': 3, 'NumWebVisitsMonth': 8, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 0, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 0, 'Age': 45, 'AgeGroup': 'Adult'}
Received: {'CustomerID': 12364, 'TotalSales': 1313.1, 'Quantity': 1506, 'NumOrders': 4, 'Customer_ID': 4939, 'BirthYear': 1946, 'Education': 'Graduation', 'Marital_Status': 'Together', 'Income': 37760.0, 'Kidhome': 0, 'Teenhome': 0, 'Dt_Customer': '31-08-2012', 'Recency': 20, 'MntWines': 84, 'MntFruits': 5, 'MntMeatProducts': 38, 'MntFishProducts': 150, 'MntSweetProducts': 12, 'MntGoldProds': 28, 'NumDealsPurchases': 2, 'NumWebPurchases': 4, 'NumCatalogPurchases': 1, 'NumStorePurchases': 6, 'NumWebVisitsMonth': 7, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 0, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 0, 'Age': 79, 'AgeGroup': 'Senior'}
Received: {'CustomerID': 12365, 'TotalSales': 320.69, 'Quantity': 173, 'NumOrders': 3, 'Customer_ID': 6565, 'BirthYear': 1949, 'Education': 'Master', 'Marital_Status': 'Married', 'Income': 76995.0, 'Kidhome': 0, 'Teenhome': 1, 'Dt_Customer': '28-03-2013', 'Recency': 91, 'MntWines': 1012, 'MntFruits': 80, 'MntMeatProducts': 498, 'MntFishProducts': 0, 'MntSweetProducts': 16, 'MntGoldProds': 176, 'NumDealsPurchases': 2, 'NumWebPurchases': 11, 'NumCatalogPurchases': 4, 'NumStorePurchases': 9, 'NumWebVisitsMonth': 5, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 1, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 0, 'Age': 76, 'AgeGroup': 'Senior'}
Received: {'CustomerID': 12367, 'TotalSales': 168.9, 'Quantity': 173, 'NumOrders': 1, 'Customer_ID': 2278, 'BirthYear': 1985, 'Education': '2n Cycle', 'Marital_Status': 'Single', 'Income': 33812.0, 'Kidhome': 1, 'Teenhome': 0, 'Dt_Customer': '03-11-2012', 'Recency': 86, 'MntWines': 4, 'MntFruits': 17, 'MntMeatProducts': 19, 'MntFishProducts': 30, 'MntSweetProducts': 24, 'MntGoldProds': 39, 'NumDealsPurchases': 2, 'NumWebPurchases': 2, 'NumCatalogPurchases': 1, 'NumStorePurchases': 3, 'NumWebVisitsMonth': 6, 'AcceptedCmp3': 0, 'AcceptedCmp4': 0, 'AcceptedCmp5': 0, 'AcceptedCmp1': 0, 'AcceptedCmp2': 0, 'Complain': 0, 'Z_CostContact': 3, 'Z_Revenue': 11, 'Response': 0, 'Age': 40, 'AgeGroup': 'Adult'}

In [7]:
running_total = 0

for message in stream_messages:

    running_total += message["TotalSales"]

    print(
        "Current Sales Total:",
        running_total
    )

Current Sales Total: 0.0
Current Sales Total: 4310.0
Current Sales Total: 6107.24
Current Sales Total: 7864.79
Current Sales Total: 8199.19
Current Sales Total: 9744.6
Current Sales Total: 9833.6
Current Sales Total: 10913.0
Current Sales Total: 11372.4
Current Sales Total: 14183.83
Current Sales Total: 20391.5
Current Sales Total: 21559.56
Current Sales Total: 27742.54
Current Sales Total: 30404.600000000002
Current Sales Total: 30594.500000000004
Current Sales Total: 35749.08
Current Sales Total: 36301.08
Current Sales Total: 37614.18
Current Sales Total: 37934.87
Current Sales Total: 38103.770000000004

In [8]:
stream_df = pd.DataFrame(
    stream_messages
)

stream_df.head()

,CustomerID,TotalSales,Quantity,NumOrders,Customer_ID,BirthYear,Education,Marital_Status,Income,Kidhome,...,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Age,AgeGroup
0,12346,0.00,0,2,5524,1957,Graduation,Single,58138.0,0,...,0,0,0,0,0,3,11,1,68,Senior
1,12347,4310.00,2458,7,2174,1954,Graduation,Single,46344.0,1,...,0,0,0,0,0,3,11,0,71,Senior
2,12348,1797.24,2341,4,4141,1965,Graduation,Together,71613.0,0,...,0,0,0,0,0,3,11,0,60,Middle Age
3,12349,1757.55,631,1,6182,1984,Graduation,Together,26646.0,1,...,0,0,0,0,0,3,11,0,41,Adult
4,12350,334.40,197,1,5324,1981,PhD,Married,58293.0,1,...,0,0,0,0,0,3,11,0,44,Adult